#!/usr/bin/env python3
import csv
from collections import Counter
from pathlib import Path

CANDIDATES = Path('tools/official_derivatives/next_10_source_candidates_candidate_10_19.tsv')
REPORT = Path('tools/official_derivatives/next_10_source_candidate_report.md')
SCORE_FIELDS = [
    'structural_rationality_score','origin_integrity_score','ai_index_fit_score',
    'human_entry_fit_score','effect_expansion_score','quality_risk_control_score'
]


def rows(path):
    with path.open(encoding='utf-8', newline='') as f:
        return list(csv.DictReader(f, delimiter='\t'))


def ready(row):
    if row.get('recommendation') != 'ready_for_queue':
        return False
    try:
        scores = [int(row.get(key, '')) for key in SCORE_FIELDS]
    except ValueError:
        return False
    return (
        row.get('source_status') == 'recommended'
        and row.get('public_safe_status') == 'pass'
        and scores[1] == 5
        and all(score >= 4 for score in scores)
        and sum(scores) >= 27
        and row.get('total_score') == str(sum(scores))
        and row.get('parent_url','').startswith('https://master.ricette.jp/')
        and row.get('parent_ncl_id','').startswith('NCL-')
        and row.get('parent_diff_id','').startswith('DIFF-')
        and row.get('canonical_url','').startswith('https://master.ricette.jp/derivatives/')
        and row.get('reason_for_inclusion','').strip() not in {'','none','pending source selection'}
        and row.get('risk_note','').strip() not in {'','none'}
    )


def main():
    candidate_rows = rows(CANDIDATES)
    status_counts = Counter(row.get('source_status','') for row in candidate_rows)
    public_counts = Counter(row.get('public_safe_status','') for row in candidate_rows)
    recommendation_counts = Counter(row.get('recommendation','') for row in candidate_rows)
    ready_rows = [row for row in candidate_rows if ready(row)]

    lines = [
        '# Candidate 10-19 Source Candidate Report',
        '',
        'release_state: source_selection_preparation_only',
        'production_deploy: false',
        'sitemap_update: false',
        'search_console: false',
        'index_follow_conversion: false',
        'page_generation: false',
        'staged_generation: false',
        '',
        '## Counts',
        '',
        f'source_candidate_rows: {len(candidate_rows)}',
        f'ready_for_queue_candidates: {len(ready_rows)}',
        '',
        '## Source status counts',
        '',
    ]
    if status_counts:
        for key in sorted(status_counts):
            lines.append(f'- {key}: {status_counts[key]}')
    else:
        lines.append('- none: 0')

    lines.extend(['', '## Public-safe status counts', ''])
    if public_counts:
        for key in sorted(public_counts):
            lines.append(f'- {key}: {public_counts[key]}')
    else:
        lines.append('- none: 0')

    lines.extend(['', '## Recommendation counts', ''])
    if recommendation_counts:
        for key in sorted(recommendation_counts):
            lines.append(f'- {key}: {recommendation_counts[key]}')
    else:
        lines.append('- none: 0')

    lines.extend([
        '',
        '## Boundary',
        '',
        'No candidate 10-19 source is selected, staged, deployed, indexed, submitted, or generated by this report.',
        'A ready_for_queue source candidate is still only permission to update the queue in a later explicit step.',
        '',
    ])
    REPORT.write_text('\n'.join(lines), encoding='utf-8')
    print('wrote=' + str(REPORT))
    print('source_candidate_rows=' + str(len(candidate_rows)))
    print('ready_for_queue_candidates=' + str(len(ready_rows)))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
