#!/usr/bin/env python3
from pathlib import Path
import csv
import sys

HERE = Path(__file__).resolve().parent
BASE = HERE.parents[1] / 'deploy/lolipop/master-ricette/derivatives'
TARGETS = HERE / 'targets.tsv'
MANIFEST = HERE / 'origin_manifest.tsv'
REGISTRY = HERE / 'derivative_registry_candidate_05_09.tsv'
REPORT = HERE / 'candidate_05_09_gate_report.md'
PAGES = ['index.html','ja/human-summary/index.html','ja/faq/index.html','ja/ai-index/index.html','en/ai-index/index.html','zh/ai-index/index.html']


def read_tsv(path):
    with path.open(encoding='utf-8', newline='') as f:
        return list(csv.DictReader(f, delimiter='\t'))


def page_count(folders):
    checked = 0
    missing = []
    for folder in folders:
        for rel in PAGES:
            path = BASE / folder / rel
            if path.exists():
                checked += 1
            else:
                missing.append(str(path))
    return checked, missing


def write_report(values):
    lines = [
        '# Candidate 05-09 Gate Report',
        '',
        'This report is generated by `tools/official_derivatives/build_batch_summary.py`.',
        '',
        '## Status',
        '',
        f"- release_state: {values['release_state']}",
        f"- production_deploy: {values['production_deploy']}",
        f"- sitemap_update: {values['sitemap_update']}",
        f"- search_console: {values['search_console']}",
        f"- index_follow_conversion: {values['index_follow_conversion']}",
        '',
        '## Counts',
        '',
        f"- active_targets: {values['active_targets']}",
        f"- staged_targets: {values['staged_targets']}",
        f"- pages_per_target: {values['pages_per_target']}",
        f"- expected_staged_pages: {values['expected_staged_pages']}",
        f"- checked_staged_pages: {values['checked_staged_pages']}",
        f"- registry_rows: {values['registry_rows']}",
        f"- manifest_rows: {values['manifest_rows']}",
        '',
        '## Boundary',
        '',
        '- candidate 05-09 remains staged and draft-bound.',
        '- generated pages must remain noindex,nofollow.',
        '- origin, parent URL, parent NCL-ID, parent Diff-ID, canonical URL, and Nakagawa Master attribution must stay attached.',
        '- registry, HTML, and listing guards must pass before any owner/publication boundary action.',
        '',
    ]
    REPORT.write_text('\n'.join(lines), encoding='utf-8')


def main():
    targets = read_tsv(TARGETS)
    manifest = read_tsv(MANIFEST)
    registry = read_tsv(REGISTRY) if REGISTRY.exists() else []
    active = [r['folder_id'] for r in targets if r.get('export_status') == 'active']
    staged = [r['folder_id'] for r in targets if r.get('export_status') == 'staged']
    checked_staged, missing = page_count(staged)
    expected_staged = len(staged) * len(PAGES)
    values = {
        'release_state': 'staged_only',
        'production_deploy': 'false',
        'sitemap_update': 'false',
        'search_console': 'false',
        'index_follow_conversion': 'false',
        'active_targets': len(active),
        'staged_targets': len(staged),
        'pages_per_target': len(PAGES),
        'expected_staged_pages': expected_staged,
        'checked_staged_pages': checked_staged,
        'registry_rows': len(registry),
        'manifest_rows': len(manifest),
    }
    write_report(values)
    print('summary_set=official_derivative_batch_v3')
    for key, value in values.items():
        print(str(key) + '=' + str(value))
    if missing:
        print('batch_summary_pass=false')
        for item in missing:
            print('missing=' + item)
        return 1
    if len(manifest) != len(targets):
        print('batch_summary_pass=false')
        print('manifest_target_count_mismatch=true')
        return 1
    print('report=' + str(REPORT))
    print('batch_summary_pass=true')
    return 0


if __name__ == '__main__':
    sys.exit(main())
