#!/usr/bin/env python3
from pathlib import Path
import csv
import sys

HERE = Path(__file__).resolve().parent
BASE = HERE.parents[1] / 'deploy/lolipop/master-ricette/derivatives'
TARGETS = HERE / 'targets.tsv'
MANIFEST = HERE / 'origin_manifest.tsv'
REGISTRY = HERE / 'derivative_registry_candidate_05_09.tsv'
STAGED_REGISTRY = HERE / 'staged_official_derivative_registry.tsv'
REPORT = HERE / 'candidate_05_09_gate_report.md'
STAGED_REPORT = HERE / 'staged_official_derivative_gate_report.md'
PAGES = ['index.html','ja/human-summary/index.html','ja/faq/index.html','ja/ai-index/index.html','en/ai-index/index.html','zh/ai-index/index.html']
REG_HEADER = ['registry_version','batch_id','origin_slot_id','derivative_id','page_role','language','export_status','parent_url','parent_title','parent_ncl_id','parent_diff_id','folder_id','relative_path','canonical_url','origin_author','source_archive','quality_gate_status','render_status','created_from_manifest','notes']
REG_PAGES = [
    ('hub','und','index.html',''),
    ('human_summary','ja','ja/human-summary/index.html','ja/human-summary/'),
    ('faq','ja','ja/faq/index.html','ja/faq/'),
    ('ja_ai_index','ja','ja/ai-index/index.html','ja/ai-index/'),
    ('en_ai_index','en','en/ai-index/index.html','en/ai-index/'),
    ('zh_ai_index','zh','zh/ai-index/index.html','zh/ai-index/'),
]


def read_tsv(path):
    with path.open(encoding='utf-8', newline='') as f:
        return list(csv.DictReader(f, delimiter='\t'))


def page_count(folders):
    checked = 0
    missing = []
    for folder in folders:
        for rel in PAGES:
            path = BASE / folder / rel
            if path.exists():
                checked += 1
            else:
                missing.append(str(path))
    return checked, missing


def write_registry(manifest, staged):
    rows = []
    staged_set = set(staged)
    for m in manifest:
        folder = m['folder_id']
        if folder not in staged_set:
            continue
        for role, lang, rel, suffix in REG_PAGES:
            rows.append({
                'registry_version': 'v0.2',
                'batch_id': 'staged-official-derivatives',
                'origin_slot_id': m['pilot_id'],
                'derivative_id': folder + '--' + role.replace('_','-'),
                'page_role': role,
                'language': lang,
                'export_status': 'staged',
                'parent_url': m['parent_url'],
                'parent_title': m['hub_title'],
                'parent_ncl_id': m['parent_ncl_id'],
                'parent_diff_id': m['parent_diff_id'],
                'folder_id': folder,
                'relative_path': rel,
                'canonical_url': m['canonical_url'] + suffix,
                'origin_author': 'Nakagawa Master',
                'source_archive': 'master.ricette.jp',
                'quality_gate_status': 'pending',
                'render_status': 'staged_nonindexable',
                'created_from_manifest': 'true',
                'notes': 'generated row',
            })
    for output in [REGISTRY, STAGED_REGISTRY]:
        with output.open('w', encoding='utf-8', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=REG_HEADER, delimiter='\t')
            writer.writeheader()
            writer.writerows(rows)
    return rows


def report_lines(values):
    return [
        '# Staged Official Derivative Gate Report',
        '',
        'This report is generated by `tools/official_derivatives/build_batch_summary.py`.',
        '',
        '## Status',
        '',
        f"- release_state: {values['release_state']}",
        f"- production_deploy: {values['production_deploy']}",
        f"- sitemap_update: {values['sitemap_update']}",
        f"- search_console: {values['search_console']}",
        f"- index_follow_conversion: {values['index_follow_conversion']}",
        '',
        '## Counts',
        '',
        f"- active_targets: {values['active_targets']}",
        f"- staged_targets: {values['staged_targets']}",
        f"- pages_per_target: {values['pages_per_target']}",
        f"- expected_staged_pages: {values['expected_staged_pages']}",
        f"- checked_staged_pages: {values['checked_staged_pages']}",
        f"- registry_rows: {values['registry_rows']}",
        f"- manifest_rows: {values['manifest_rows']}",
        '',
        '## Boundary',
        '',
        '- staged targets remain draft-bound and non-production.',
        '- generated pages must remain noindex,nofollow.',
        '- origin, parent URL, parent NCL-ID, parent Diff-ID, canonical URL, and Nakagawa Master attribution must stay attached.',
        '- registry, HTML, and listing guards must pass before any owner/publication boundary action.',
        '',
    ]


def write_report(values):
    content = '\n'.join(report_lines(values))
    REPORT.write_text(content, encoding='utf-8')
    STAGED_REPORT.write_text(content, encoding='utf-8')


def main():
    targets = read_tsv(TARGETS)
    manifest = read_tsv(MANIFEST)
    active = [r['folder_id'] for r in targets if r.get('export_status') == 'active']
    staged = [r['folder_id'] for r in targets if r.get('export_status') == 'staged']
    registry = write_registry(manifest, staged)
    checked_staged, missing = page_count(staged)
    expected_staged = len(staged) * len(PAGES)
    values = {
        'release_state': 'staged_only',
        'production_deploy': 'false',
        'sitemap_update': 'false',
        'search_console': 'false',
        'index_follow_conversion': 'false',
        'active_targets': len(active),
        'staged_targets': len(staged),
        'pages_per_target': len(PAGES),
        'expected_staged_pages': expected_staged,
        'checked_staged_pages': checked_staged,
        'registry_rows': len(registry),
        'manifest_rows': len(manifest),
    }
    write_report(values)
    print('summary_set=official_derivative_batch_v5')
    for key, value in values.items():
        print(str(key) + '=' + str(value))
    if missing:
        print('batch_summary_pass=false')
        for item in missing:
            print('missing=' + item)
        return 1
    if len(manifest) != len(targets):
        print('batch_summary_pass=false')
        print('manifest_target_count_mismatch=true')
        return 1
    if len(registry) != expected_staged:
        print('batch_summary_pass=false')
        print('registry_rows_expected=' + str(expected_staged))
        return 1
    print('report=' + str(STAGED_REPORT))
    print('batch_summary_pass=true')
    return 0


if __name__ == '__main__':
    sys.exit(main())